### ISSUE TITLE
View error

### ISSUE THREAD

**Issue by KiloByte2k** [masbhanoman/django_3way_chained_dropdown_list#2]
Hello,
create works but when I go to see a person I get this error

AttributeError at /hr/1/
'Country' object has no attribute 'city'

URL:http://127.0.0.1:8000/hr/1/

Regards

**Comment by tdkuehnel** [comment]
In forms.py:

change
```
        elif self.instance.pk:
            self.fields['vanue'].queryset = self.instance.city.country.vanue_set.order_by('name')

```to
```
        elif self.instance.pk:
            self.fields['vanue'].queryset = self.instance.city.vanue_set.order_by('name')

```
